import "bootstrap/dist/css/bootstrap.css";
import "../../styles/styles.css";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import Root from "@/ui/root";
import Sidebar from "@/ui/layout/sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es" data-bs-theme="dark">
            <body
                className={`${geistSans.variable} ${geistMono.variable}`}
                style={{ height: "auto" }}
            >
                <Root>
                    <div className="d-flex" style={{ minHeight: "100vh" }}>
                        <Sidebar />
                        {children}
                    </div>
                </Root>
            </body>
        </html>
    );
}
